# Generated by Django 4.1.3 on 2022-11-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
    ]
