# Generated by Django 4.1.3 on 2022-11-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list_app", "0002_alter_tags_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasks",
            options={
                "ordering": ["is_complete", "created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AlterField(
            model_name="tasks",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
