# Generated by Django 4.1.3 on 2022-11-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list_app", "0003_alter_tasks_options_alter_tasks_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="tags",
        ),
        migrations.AddField(
            model_name="tasks",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="todo_list_app.tags"),
        ),
    ]
